# This is a reusable workflow supposed to automate the version bump in the Crowdin's repositories
# See the workflow example at the end of this file
#
# It uses the 'release-it' cli + 'release-it-regex-bumper' plugin:
#   - https://www.npmjs.com/package/release-it
#   - https://www.npmjs.com/package/@j-ulrich/release-it-regex-bumper
#
# It requires the '.release-it.json' config in the repository root
#
name: Bump version
run-name: Bump ${{ github.event.inputs.version }} version

on:
  workflow_call:

jobs:
    bump:
      runs-on: ubuntu-latest

      steps:
        - uses: actions/checkout@v4

        - name: Install release-it globally
          run: |
            npm i -g release-it
            npm i -g @j-ulrich/release-it-regex-bumper
            npm i -g @release-it/keep-a-changelog
            npm i -g @release-it/conventional-changelog

        - name: git config
          run: |
            git config user.name "${GITHUB_ACTOR}"
            git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"

        - name: Bump version
          run: npx release-it --no-changelog --increment ${{ github.event.inputs.version }} --ci -V
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            NODE_DEBUG: release-it:*

# Usage example
#
# name: Bump version
# run-name: Bump ${{ github.event.inputs.version }} version
#
# on:
#   workflow_dispatch:
#     inputs:
#       version:
#         type: choice
#         description: Version
#         options:
#           - patch
#           - minor
#           - major
#
#  jobs:
#   version:
#     permissions:
#       contents: write
#     uses: crowdin/.github/.github/workflows/bump-version.yml@main
